/**
 * @description Woman
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 * @note        Auto-generated by: https://github.com/pmndrs/gltfjsx
 * @note        Command: `npx gltfjsx@6.5.3 public/model/woman.gltf`
 */
import * as THREE from 'three'
import React, {useEffect} from 'react'
import {useGraph} from '@react-three/fiber'
import {useGLTF, useAnimations} from '@react-three/drei'
import {SkeletonUtils} from 'three-stdlib'

export const Woman: React.FC<{animation: number}> = ({animation}) => {
  const group = React.useRef<THREE.Group>(null)
  const {scene, animations} = useGLTF('/r3f-character-dance/model/woman.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const {nodes, materials} = useGraph(clone)
  const {actions, names} = useAnimations(animations, group)

  useEffect(() => {
    actions[names[animation]]?.reset().fadeIn(0.5).play()
    return () => {
      actions[names[animation]]?.fadeOut(0.5)
    }
  }, [animation])

  return (
    <group name="Model" ref={group} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="SM_Chr_Developer_Female_02">
            <skinnedMesh
              castShadow={true}
              name="Mesh019"
              geometry={(nodes as any).Mesh019.geometry}
              material={materials.Glasses}
              skeleton={(nodes as any).Mesh019.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_1"
              geometry={(nodes as any).Mesh019_1.geometry}
              material={materials.Eyes}
              skeleton={(nodes as any).Mesh019_1.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_2"
              geometry={(nodes as any).Mesh019_2.geometry}
              material={materials.Hair}
              skeleton={(nodes as any).Mesh019_2.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_3"
              geometry={(nodes as any).Mesh019_3.geometry}
              material={materials.Skin}
              skeleton={(nodes as any).Mesh019_3.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_4"
              geometry={(nodes as any).Mesh019_4.geometry}
              material={materials.Mouth}
              skeleton={(nodes as any).Mesh019_4.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_5"
              geometry={(nodes as any).Mesh019_5.geometry}
              material={materials.Shirt}
              skeleton={(nodes as any).Mesh019_5.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_6"
              geometry={(nodes as any).Mesh019_6.geometry}
              material={materials.Pants}
              skeleton={(nodes as any).Mesh019_6.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_7"
              geometry={(nodes as any).Mesh019_7.geometry}
              material={materials.Shoes}
              skeleton={(nodes as any).Mesh019_7.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_8"
              geometry={(nodes as any).Mesh019_8.geometry}
              material={materials.Sole}
              skeleton={(nodes as any).Mesh019_8.skeleton}
            />
            <skinnedMesh
              castShadow={true}
              name="Mesh019_9"
              geometry={(nodes as any).Mesh019_9.geometry}
              material={materials.Laces}
              skeleton={(nodes as any).Mesh019_9.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/r3f-character-dance/model/woman.gltf')
